-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.covid
(
    week integer,
    state character varying COLLATE pg_catalog."default" NOT NULL,
    week_start date NOT NULL,
    covid_d integer,
    pneum_d integer,
    flu_d integer,
    anyof3_d integer,
    total_d integer,
    poe_d double precision,
	year integer
);
END;

select * from covid;